const colors = require('tailwindcss/colors');

module.exports = {
  purge: [
    './content/*.md',
    './content/**/*.md',
    './static/**/*.html',
    './themes/**/*.html',
    './sources/**/*.tsx',
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    fontFamily: {
      sans: ["Titillium Web", "ui-sans-serif", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "Noto Sans", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"],
      mono: ["Roboto Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
      serif: ["ui-serif", "Georgia", "Cambria", "Times New Roman", "Times", "serif"],
      readable: ["ui-sans-serif", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "Noto Sans", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"]
    },
    colors: {
      'covalent-pink': '#FF4C8B',
      'covalent-pink-light': "#ff93b9",
      'covalent-blue': {
        light: '#5290F7',
        DEFAULT: '#52AEE5',
        dark: '#000426',
      },
      'covalent-purple': {
        dark: '#25275B',
        gradient: '#191b3e',
      },
      'covalent-gray': {
        light: '#f5f5f5',
        DEFAULT: '#868e96',
        dark: '#2D2D2D',
      },
      'covalent-black': {
        DEFAULT: '#0F0F0F',
      },
      'covalent-green': '#a9c270',
      'covalent-teal': '#00D8D5',
      'covalent-yellow': '#ffca00',
      transparent: '#191b3e00',
      white: {
        DEFAULT: '#fff',
        transparent: '#ffffff40',
      },
      black: '#000',
      gray: colors.trueGray
    },
    fontSize: {
      "xxs": [".50rem", { lineHeight: "0.75rem", letterSpacing: "0em" }],
      "xs": [".75rem", { lineHeight: "1rem", letterSpacing: "0em" }],
      "sm": [".875rem", { lineHeight: "1.25rem", letterSpacing: "0em" }],
      "base": ["1rem", { lineHeight: "1.5rem", letterSpacing: "0em" }],
      "lg": ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "0.02em" }],
      "xl": ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "0.02em" }],
      "2xl": ["1.5rem", { lineHeight: "2rem", letterSpacing: "0em" }],
      "3xl": ["1.5rem", { lineHeight: "2rem", letterSpacing: "0em" }],
      "4xl": ["2.18rem", { lineHeight: "3rem", letterSpacing: "0em" }],
      "5xl": ["2.18rem", { lineHeight: "3rem", letterSpacing: "0em" }],
      "6xl": ["4rem", { lineHeight: "4.5rem", letterSpacing: "0em" }],
    },
    letterSpacing: {
      tightest: "-.075em",
      tighter: "-.05em",
      tight: "-.025em",
      normal: "0.025em",
      wide: ".08em",
      wider: ".2em",
      widest: ".5em",
    },
    maxHeight: {
      '8': '2rem',
      '96': '24rem',
      'xl': '40rem',
    },
    maxWidth: {
      '0': "0rem",
      'none': "none",
      'xs': "20rem",
      'sm': "24rem",
      'md': "28rem",
      'lg': "32rem",
      'xl': "36rem",
      '2xl': "42rem",
      '3xl': "48rem",
      '4xl': "56rem",
      '5xl': "64rem",
      '6xl': "72rem",
      '7xl': "80rem",
      'full': "100%",
      'min': "min-content",
      'max': "max-content",
      'prose': "65ch",
      'screen-sm': "640px",
      'screen-md': "768px",
      'screen-lg': "1024px",
      'screen-xl': "1280px",
      'screen-2xl': "1536px",
    },
    extend: {
      backgroundImage: theme => ({
        'hero-large': 'url(/static/images/backgrounds/Particles_large.jpg)',
        'hero-medium': 'url(/static/images/backgrounds/Particles_medium.jpg)',
        'hero-small': 'url(/static/images/backgrounds/Particles_small.jpg)',
        'hero-alt-large': 'url(/static/images/backgrounds/Concentric_large.jpg)',
        'hero-alt-medium': 'url(/static/images/backgrounds/Concentric_medium.jpg)',
        'hero-alt-small': 'url(/static/images/backgrounds/Concentric_small.jpg)',
        'ambassador': 'url(/static/images/ambassadors/ambassadorsv2.jpg)',
        'ambassador-slim': 'url(/static/images/ambassadors/ambassadors_slimv2.jpg)',
        'particle-alt-large': 'url(/static/images/backgrounds/Particles_alt_largev2.jpg)',
        'particle-alt': 'url(/static/images/backgrounds/Particles_alt.jpg)',
        'particle-alt-mobile': 'url(/static/images/backgrounds/Particles_alt_mobile.png)',
        'particle-large-black': 'url(/static/images/backgrounds/Particles_large_blackv2.jpg)',
        'particle-large-white': 'url(/static/images/backgrounds/Particles_large_white.jpg)',
        'particle-large-red': 'url(/static/images/backgrounds/Particles_red_large.jpg)',
        'particle-medium-red': 'url(/static/images/backgrounds/Particles_red_medium.jpeg)',
        'particle-small-red': 'url(/static/images/backgrounds/Particles_red_small.jpeg)',
        'fibreoptics-large': 'url(/static/images/backgrounds/Fibreoptics_large.jpg)',
        'fibreoptics-alt': 'url(/static/images/backgrounds/Fibreoptics_alt_large.jpg)',
        'fibreoptics-alt-mobile': 'url(/static/images/backgrounds/Fibreoptics_alt_mobile.jpg)',
        'bg-intro': 'url(/static/images/backgrounds/BG_opt.jpg)',
        'particle-fibreoptics': 'url(/static/images/backgrounds/Particles_Fibreoptics_.jpg)',
        'fibreoptics-1': 'url(/static/images/backgrounds/Fiberoptics_1.jpg)',
        'fibreoptics-2': 'url(/static/images/backgrounds/Fiberoptics_2.jpg)',
        'fibreoptics-3': 'url(/static/images/backgrounds/Fiberoptics_3.jpg)',
        'fibreoptics-4': 'url(/static/images/backgrounds/Fiberoptics_4.jpg)',
        'fibreoptics-5': 'url(/static/images/backgrounds/Fiberoptics_5.jpg)',
        'fibreoptics-6': 'url(/static/images/backgrounds/Particles_Fibreoptics_6.jpg)',
        'fibreoptics-7': 'url(/static/images/backgrounds/Fiberoptics_7.jpg)',
        'fibreoptics-8': 'url(/static/images/backgrounds/Fiberoptics_8.jpg)',
        'fibreoptics-9': 'url(/static/images/backgrounds/Fiberoptics_9.jpg)',
        'fibreoptics-10': 'url(/static/images/backgrounds/Fibreoptics_10.jpg)',
        'y-spiral-hz': 'url(/static/images/backgrounds/y-spiral-hz.jpg)',
        'index-1': 'url(/static/images/backgrounds/Index_1.jpg)',
        'index-9': 'url(/static/images/backgrounds/Index_9.jpg)',
        'index-8': 'url(/static/images/backgrounds/Index_8.jpg)',
        'background-10': 'url(/static/images/backgrounds/Covalent-Background_11.jpg)',
        'background-5': 'url(/static/images/backgrounds/Covalent-Background_5.jpg)',
        'background-6': 'url(/static/images/backgrounds/Covalent-Background_6.png)',
        'vijay': 'url(/static/images/token/vijay.jpg)',
        'eric': 'url(/static/images/token/eric.jpg)',
        'tm': 'url(/static/images/token/tm.jpeg)',
        'idon': 'url(/static/images/token/idon.jpeg)',
        'daniel': 'url(/static/images/token/daniel.jpeg)',
        'bg-1': 'url(/static/images/backgrounds/bg-1.jpg)',
        'bg-2': 'url(/static/images/backgrounds/bg-2.jpg)',
        'bg-3': 'url(/static/images/backgrounds/bg-3.jpg)',
        'bg-4': 'url(/static/images/backgrounds/bg-4.jpg)',
        'bg-5': 'url(/static/images/backgrounds/bg-5.jpg)',
        'bg-6': 'url(/static/images/backgrounds/Index-1.jpg)',
        'bg-7': 'url(/static/images/backgrounds/bg-7.jpg)',
        'bg-10': 'url(/static/images/backgrounds/bg-10.jpg)',
        'pixel-1': 'url(/static/images/backgrounds/Pixelart-background.jpg)',
        'pixel-2': 'url(/static/images/backgrounds/Pixelart-background-2.jpg)',
        'pixel-3': 'url(/static/images/backgrounds/Pixelart-background-3.jpg)',
        'pixel-4': 'url(/static/images/backgrounds/S2_Bg.jpg)',
      })
    },
    screens: {
      // just three devices: mobile, tablet and desktop
      'sm': { 'min': '0px', 'max': '600px' },
      'md': { 'min': '601px', 'max': '1024px' },
      'lg': '1025px',
    },
    zIndex: {
      '-10': '-10',
      '-1': "-1",
      '0': 0,
      '10': 10,
      '20': 20,
      '30': 30,
      '40': 40,
      '50': 50,
      '25': 25,
      '50': 50,
      '75': 75,
      '80': 80,
      '100': 100,
      'auto': 'auto',
    }
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/line-clamp'),
    require('@tailwindcss/aspect-ratio'),
    require('tailwindcss-border-gradient-radius'),
  ]
};
